"""alter table column hash default

Revision ID: 28f671c58622
Revises: cc9fce486751
Create Date: 2022-08-01 19:53:31.669093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f671c58622'
down_revision = 'cc9fce486751'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
